backend:
  name: git-gateway
  branch: main # تأكد أن هذا هو اسم الفرع الرئيسي في GitHub

media_folder: "assets/images"
public_folder: "/assets/images"

collections:
  - name: "products"
    label: "المنتجات"
    folder: "content/products"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "اسم المنتج", name: "title", widget: "string"}
      - {label: "السعر", name: "price", widget: "string"}
      - {label: "صورة المنتج", name: "image", widget: "image"}
      - {label: "رابط الطلب (واتساب)", name: "link", widget: "string"}
      - {label: "الوصف", name: "body", widget: "markdown"}